framework:
  charset:       UTF-8
  error_handler: null
  csrf_protection:
    enabled: true
    secret: xxxxxxxxxx
  router:        { resource: "%kernel.root_dir%/config/routing.yml" }
  validation:    { enabled: true, annotations: true }
  templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
  session:
    default_locale: en
    lifetime:       3600
    auto_start:     true

twig:
  debug:            %kernel.debug%
  strict_variables: %kernel.debug%

doctrine_mongo_db:
  auto_generate_hydrator_classes: true
  auto_generate_proxy_classes: true
  default_database: expences
  document_managers:
    default:
      mappings:
        ExpencesBundle: {type: annotation}
  connections:
    default:
      server: "mongodb://exp:asdf@flame.mongohq.com:27088/expences"
      options:
        connect: true

#doctrine.config:
#  dbal:
#    default_connection: ~

security:
  providers:
    custom_provider:
      id: exp.mongodb.provider
  encoders:
    "Application\ExpencesBundle\Document\User": sha1
  firewalls:
    public:
      pattern: /login
      security: false
    main:
      pattern: .*
      logout: true
      form_login:
        always_use_default_target_path: true
        default_target_path: /

services:
  exp.mongodb.provider:
    parent: doctrine.odm.mongodb.security.user.provider
    arguments: [ExpencesBundle:User, username]
