app.config:
  charset:       UTF-8
  error_handler: null
  csrf_secret:   xxxxxxxxxx
  router:        { resource: "%kernel.root_dir%/config/routing.yml" }
  validation:    { enabled: true, annotations: true }
  templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
  security:      {}
  session:
    default_locale: en
    lifetime:       3600
    auto_start:     true

twig.config:
  debug:            %kernel.debug%
  strict_variables: %kernel.debug%

doctrine_odm.mongodb:
  auto_generate_hydrator_classes: true
  auto_generate_proxy_classes: true
  mappings:
    ExpencesBundle: {type: annotation}
  default_database: expences
  connections:
    default:
      server: "mongodb://exp:asdf@flame.mongohq.com:27088/expences"
      options:
        connect: true

#doctrine.config:
#  dbal:
#    default_connection: ~

security.config:
  providers:
    default:
      document: {class: ExpencesBundle:User, property: username}
  encoders:
    "Application\ExpencesBundle\Document\User": sha1
  firewalls:
    public:
      pattern: /login
      security: false
    main:
      pattern: .*
      logout: true
      form_login:
        always_use_default_target_path: true
        default_target_path: /
