operations:
  pattern:  /
  defaults: { _controller: ExpencesBundle:Operations:index}

operation_new:
  pattern:  /new
  defaults: { _controller: ExpencesBundle:Operations:new}

manage_tags:
  pattern: /manage/tags/{operationId}
  defaults: {_controller: ExpencesBundle:Operations:manageTags}

save_tags:
  pattern: /tags/save
  defaults: {_controller: ExpencesBundle:Operations:saveTags}

upload:
  pattern: /upload
  defaults: {_controller: ExpencesBundle:Operations:upload}

stats_monthly_graph:
  pattern: /stats/monthly/graph
  defaults: {_controller: ExpencesBundle:Stats:monthlyGraph}

stats_yearly_graph:
  pattern: /stats/yearly/graph
  defaults: {_controller: ExpencesBundle:Stats:yearlyGraph}

tags_monthly_graph:
  pattern: /stats/tags/graph
  defaults: {_controller: ExpencesBundle:Stats:tagsGraph}
